# Generated by Django 5.2.9 on 2025-12-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0003_pdfsession_original_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFAIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('key_points', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='Teacher.pdfsession')),
            ],
        ),
    ]
