# Generated by Django 5.2.9 on 2026-01-31 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFAIResult',
        ),
    ]
