# Generated by Django 5.2.9 on 2025-12-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfsession',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
