# Generated by Django 5.2.9 on 2025-12-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_pdfsession_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfsession',
            name='original_file_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdfsession',
            name='file_path',
            field=models.CharField(max_length=500),
        ),
    ]
